[phases.setup]
nixPkgs = ["nodejs_20", "ffmpeg", "nss", "freetype", "harfbuzz", "fontconfig", "xorg.libX11", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXext", "xorg.libXrandr", "xorg.libXtst", "glib", "dbus", "at-spi2-atk", "cups", "libdrm", "mesa", "expat", "alsa-lib", "pango", "cairo", "gtk3"]
