[phases.setup]
nixPkgs = ["nodejs_20", "ffmpeg", "chromium", "nss", "freetype", "harfbuzz", "ca-certificates", "fontconfig"]

[variables]
PUPPETEER_SKIP_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/nix/var/nix/profiles/default/bin/chromium"
